KMS: add KMS support
inhabitedtype/ocaml-aws pull request #118
Opened 2021-12-17 21:53 UTC by zbaylin

This adds support for AWS's Key Management Service.

Unfortunately the service definitions provided by botocore do not provide the necessary `resultWrappers` (https://github.com/boto/botocore/issues/2576), so I had to modify the override system a bit to add those in.

2022-03-30 23:01 UTC, tmcgilchrist requested changes
Really nice work @zbaylin, the overriding of the resultWrapper looks right.

Could I ask you to squash your work into 2 commits; 1 for the fixes to the generator and associated botocore overrides, and a second commit that just includes the generated code.

Please include a line in the CHANGES.md under `#Unreleased` with a short description of your changes and a link back to this PR. Many thanks for the contribution.

2022-04-01 21:14 UTC, zbaylin commented
@tmcgilchrist sure! I'll do that and force push.

Thanks for the review!

2022-04-03 21:57 UTC, tmcgilchrist approved these changes

2022-04-03 21:58 UTC, merged

2022-04-03 23:41 UTC, tmcgilchrist commented
@zbaylin I'll include this library in the next aws release 1.2.1 https://github.com/inhabitedtype/ocaml-aws/issues/110